Update howl-spec to work with the latest busted

diff --git a/bin/howl-spec b/bin/howl-spec
--- a/bin/howl-spec
+++ b/bin/howl-spec
@@ -16,21 +16,31 @@ if [ -z "$HOWL" ]; then
   exit 1
 fi
 
-if command -v busted > /dev/null 2>/dev/null; then
-  export BUSTED='yes'
-  exec busted -l $HOWL --pattern=_spec.moon $*
-else
-  cat <<ERR
-Error: 'busted' command not found
+busted=$(luarocks list busted|grep installed|head -n 1)
+if [ -n "$busted" ]; then
+  version=$(echo "$busted" | awk '{ print $1 }')
+  path=$(echo "$busted" | awk '{ print $4 }')
+  busted_script="$path/busted/$version/bin/busted_bootstrap"
+  if [ ! -f $busted_script ]; then
+    busted_script="$path/busted/$version/bin/busted"
+  fi
+
+  if [ -f $busted_script ]; then
+    export BUSTED='yes'
+    exec $HOWL $busted_script --pattern=_spec.moon $*
+  fi
+fi
+
+cat <<ERR
+Error: 'busted' not found
 ---------------------------------
 
-To run $0 you need to have the busted testing framework installed.
-The easiest way of doing this is to install luarocks, and execute:
+To run $0 you need to have the busted testing framework installed via luarocks.
+With luarocks installed, execute:
 
 $ luarocks install busted
 
 luarocks might be available from your package manager, or you can install
 it using the instructions from http://luarocks.org
 ERR
-  exit 1
-fi
+exit 1
